### ISSUE TITLE
Won't compile on Windows 8.1 (32 bits) Python 3.5.2

### ISSUE THREAD

**Issue by silvium** [jflesch/pyinsane#26]
I got past the first compilation issue (missing "atlbase.h") by installing Windows Driver Kit, but now I get too much of a generic error:

` C:\>pip3 install pyinsane2
Collecting pyinsane2
  Using cached pyinsane2-2.0.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): Pillow in c:\users\administrator\appdata\local\programs\python\python35-32\lib\site-packages (from pyinsane2)
Installing collected packages: pyinsane2
  Running setup.py install for pyinsane2 ... error
    Complete output from command c:\users\administrator\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-build-7f56p3zo\\pyinsane2\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\pip-wmnd2g65-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.5
    creating build\lib.win32-3.5\pyinsane2
    copying src\pyinsane2\util.py -> build\lib.win32-3.5\pyinsane2
    copying src\pyinsane2\__init__.py -> build\lib.win32-3.5\pyinsane2
    creating build\lib.win32-3.5\pyinsane2\sane
    copying src\pyinsane2\sane\abstract.py -> build\lib.win32-3.5\pyinsane2\sane
    copying src\pyinsane2\sane\abstract_proc.py -> build\lib.win32-3.5\pyinsane2\sane
    copying src\pyinsane2\sane\daemon.py -> build\lib.win32-3.5\pyinsane2\sane
    copying src\pyinsane2\sane\rawapi.py -> build\lib.win32-3.5\pyinsane2\sane
    copying src\pyinsane2\sane\__init__.py -> build\lib.win32-3.5\pyinsane2\sane
    creating build\lib.win32-3.5\pyinsane2\wia
    copying src\pyinsane2\wia\abstract.py -> build\lib.win32-3.5\pyinsane2\wia
    copying src\pyinsane2\wia\rawapi.py -> build\lib.win32-3.5\pyinsane2\wia
    copying src\pyinsane2\wia\__init__.py -> build\lib.win32-3.5\pyinsane2\wia
    running build_ext
    building 'pyinsane2.wia._rawapi' extension
    creating build\temp.win32-3.5
    creating build\temp.win32-3.5\Release
    creating build\temp.win32-3.5\Release\src
    creating build\temp.win32-3.5\Release\src\pyinsane2
    creating build\temp.win32-3.5\Release\src\pyinsane2\wia
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -UNDEBUG -Ic:\winddk\7600.16385.1\inc\atl71 -Ic:\users\administrator\appdata\local\programs\python\python35-32\include -Ic:\users\administrator\appdata\local\programs\python\python35-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program
Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tpsrc/pyinsane2/wia/properties.cpp /Fobuild\temp.win32-3.5\Release\src/pyinsane2/wia/properties.obj /W4
    cl : Command line warning D9025 : overriding '/DNDEBUG' with '/UNDEBUG'
    cl : Command line warning D9025 : overriding '/W3' with '/W4'
    properties.cpp
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -UNDEBUG -Ic:\winddk\7600.16385.1\inc\atl71 -Ic:\users\administrator\appdata\local\programs\python\python35-32\include -Ic:\users\administrator\appdata\local\programs\python\python35-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program
Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tpsrc/pyinsane2/wia/rawapi.cpp /Fobuild\temp.win32-3.5\Release\src/pyinsane2/wia/rawapi.obj /W4
    cl : Command line warning D9025 : overriding '/DNDEBUG' with '/UNDEBUG'
    cl : Command line warning D9025 : overriding '/W3' with '/W4'
    rawapi.cpp
    c:\winddk\7600.16385.1\inc\atl71\atlcomcli.h(414): warning C4838: conversion from 'int' to 'UINT' requires a narrowing conversion
    c:\users\administrator\appdata\local\temp\pip-build-7f56p3zo\pyinsane2\src\pyinsane2\wia\transfer.h(50): error C2695: 'PyinsaneWiaTransferCallback::GetNextStream': overriding virtual function differs from 'IWiaTransferCallback::GetNextStream' only by calling convention
    C:\Program Files (x86)\Windows Kits\8.1\include\um\wia_lh.h(2990): note: see declaration of 'IWiaTransferCallback::GetNextStream'
    c:\users\administrator\appdata\local\temp\pip-build-7f56p3zo\pyinsane2\src\pyinsane2\wia\transfer.h(51): error C2695: 'PyinsaneWiaTransferCallback::TransferCallback': overriding virtual function differs from 'IWiaTransferCallback::TransferCallback' only by calling convention
    C:\Program Files (x86)\Windows Kits\8.1\include\um\wia_lh.h(2986): note: see declaration of 'IWiaTransferCallback::TransferCallback'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\administrator\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-build-7f56p3zo\\pyinsane2\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\pip-wmnd2g65-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-7f56p3zo\pyinsane2\`

**Comment by jflesch** [comment]
Argh .. Microsoft own libraries don't compile with /w4 ... Anyway, it's my fault, I shouldn't have released it with /w4.

I've disabled /w4. Can you clone ```https://github.com/jflesch/pyinsane.git``` and try it please ?
(right now I don't have a VM with Windows 8.1)

By the way, which version of Visual C++ do you use ?

**Comment by silvium** [comment]
I'm using Microsoft Visual C++ Build Tools 2015, it seems to include Visual C++ 14.0. If there's anything else you'd recommend I'm open to trying.

Now I'm getting: 
`D:\git\pyinsane>python setup.py install
running install
running bdist_egg
running egg_info
writing dependency_links to pyinsane2.egg-info\dependency_links.txt
writing pyinsane2.egg-info\PKG-INFO
writing top-level names to pyinsane2.egg-info\top_level.txt
writing requirements to pyinsane2.egg-info\requires.txt
reading manifest file 'pyinsane2.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.glade' under directory 'src'
warning: no files found matching '*.xml' under directory 'src'
warning: no files found matching '*.css' under directory 'src'
warning: no files found matching 'example-paperwork.conf'
writing manifest file 'pyinsane2.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
running build_ext
building 'pyinsane2.wia._rawapi' extension
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -UNDEBUG -Ic:\winddk\7600.16385.1\inc\atl71 -IC:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tpsrc/pyinsane2/wia/properties.cpp /Fobuild\temp.win32-3.5\Release\src/pyinsane2/wia/properties.obj
cl : Command line warning D9025 : overriding '/DNDEBUG' with '/UNDEBUG'
properties.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -UNDEBUG -Ic:\winddk\7600.16385.1\inc\atl71 -IC:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tpsrc/pyinsane2/wia/rawapi.cpp /Fobuild\temp.win32-3.5\Release\src/pyinsane2/wia/rawapi.obj
cl : Command line warning D9025 : overriding '/DNDEBUG' with '/UNDEBUG'
rawapi.cpp
c:\winddk\7600.16385.1\inc\atl71\atlcomcli.h(414): warning C4838: conversion from 'int' to 'UINT' requires a narrowing
conversion
z:\dev\git\pyinsane\src\pyinsane2\wia\transfer.h(50): error C2695: 'PyinsaneWiaTransferCallback::GetNextStream': overriding virtual function differs from 'IWiaTransferCallback::GetNextStream' only by calling convention
C:\Program Files (x86)\Windows Kits\8.1\include\um\wia_lh.h(2990): note: see declaration of 'IWiaTransferCallback::GetNextStream'
z:\dev\git\pyinsane\src\pyinsane2\wia\transfer.h(51): error C2695: 'PyinsaneWiaTransferCallback::TransferCallback': overriding virtual function differs from 'IWiaTransferCallback::TransferCallback' only by calling convention
C:\Program Files (x86)\Windows Kits\8.1\include\um\wia_lh.h(2986): note: see declaration of 'IWiaTransferCallback::TransferCallback'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2` 

Any... chance of a wheel? :)

**Comment by jflesch** [comment]
Unfortunately, for the wheel, I need the same environment than you (Windows version + Python). This is why there is no wheel currently for Python 3.5.
I'm going to install a VM with Python 3.5 and Visual C++ 2014 and have  a look, but it will take me time (I have a busy week-end planned).

I'm actually wondering whether Winddk is really required here.

**Comment by jflesch** [comment]
Ok, it's confirmed, I have winddk 7600.16385.1 installed.

**Comment by jflesch** [comment]
(Note: currently I work with Python 3.4 only because Gtk is only available for 3.4 for now, and I need it for Paperwork. I'm building a VM with Python 3.5 to have a look at the problem you describe)

**Comment by jflesch** [comment]
I've uploaded a wheel for Python 3.5 + amd64 (built with Windows 10 + SDK 8.1).
Can you try it and tell me if it works for you please ?

**Comment by silvium** [comment]
Yes, it works perfectly, but i could only test it on a Windows 10 PC (I have a few scripts that I need 32bit Python for on the Windows 8.1 PC that I was doing the initial tests on).

I'm extremely impressed  by your promptness and willingness to help. Have a nice weekend!

**Comment by jflesch** [comment]
Ok, got it. Your problem comes actually from the architecture. I've work exclusively with x64 up to now. When compiling on x86, I get the same error than you.

**Comment by jflesch** [comment]
I forgot "STDMETHODCALLTYPE" on the two methods indicated in the error .... :/
I've uploaded a wheel for Python 3.5 + 32bits. Please tell me if it works for you.

**Comment by jflesch** [comment]
I'm not sure I'll be able to provide a wheel for Python 3.4 32bits. Windows SDK 7.1 is painfully hard to install..

**Comment by silvium** [comment]
Works on the 32bit Python too. I got a hanging console with the following text, but it only happened twice in the beginning and I couldn't replicate it after:

`Scanning ...
|C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pyinsane2\wia\rawapi.py:181: RuntimeWarning: Pyinsane: WARNING: source->transfer->Download() failed
  out.buffer,
Pyinsane: WARNING: source->transfer->Download() failed
Pyinsane: WARNING: source->transfer->Download() failed: -2147023170 ; The remote procedure call failed.`

So I can only say it works "almost" perfectly :)

**Comment by jflesch** [comment]
Just out of curiosity, could you paste me the output of ```python examples/list_all.py``` please ? I would be curious to know which scanner you use exactly and which options it does provide.

**Comment by silvium** [comment]
I printed it to a file, too much for my console:
[list_all.txt](https://github.com/jflesch/pyinsane/files/576674/list_all.txt)

**Comment by jflesch** [comment]
Thanks :)

**Comment by jflesch** [comment]
I'm closing this ticket. If it becomes clear that the remaining problems you have are actually due to Pyinsane, please comment again here, and I will reopen this ticket.
